# AUTOGENERATED! DO NOT EDIT! File to edit: ../fastai_sitting_standing_gradio_app.ipynb.

# %% auto 0
__all__ = ['path', 'learn_inf', 'categories', 'image', 'label', 'iface', 'image_classifier']

# %% ../fastai_sitting_standing_gradio_app.ipynb 1
from fastai.vision.all import *
from fastai.learner import load_learner
import gradio as gr

# %% ../fastai_sitting_standing_gradio_app.ipynb 3
path = Path()
learn_inf = load_learner(path/'export.pkl')

# %% ../fastai_sitting_standing_gradio_app.ipynb 4
categories = ('Sitting', 'Standing')

image = gr.Image(shape=(192,192))
label = gr.Label()

def image_classifier(inp):    
    pred, idx, probs = learn_inf.predict(inp)
    return dict(zip(categories, map(float, probs)))


iface = gr.Interface(fn=image_classifier, inputs=image, outputs=label)

iface.launch()
